### PR TITLE
Fixed Issue #11 with Samsung EVO 32GB cards

### PR DESCRIPTION
**Pull request by devoh747**
and also added dynamic CRC checking

### CODE REVIEW

**Comment by devoh747** [comment]
why is this failing?  It's working on my board(GrandCentral)..  or is this to do with the mess I made of the PR's and deleting my repo?

**Comment by makermelissa** [comment]
It looks like it's failing at Pylint, which makes sure your code is consistent. You should be able to see the build log by clicking some links to see the travis logs.

Here's the particular lines:
```
C:474, 0: Exactly one space required after comma
            for _ in range(1,8):
                            ^ (bad-whitespace)
C:459, 4: Missing method docstring (missing-docstring)
C:464, 8: Variable name "CRCTable" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
C:466, 8: Variable name "CRCPoly" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
C:479, 8: Variable name "CRC" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
C:480, 8: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
C:481,12: Variable name "CRC" doesn't conform to '(([a-z][a-z0-9_]{2,30})|(_[a-z0-9_]*))$' pattern (invalid-name)
R:459, 4: Method could be a function (no-self-use)
```

**Comment by devoh747** [comment]
ok I fixed the pylint issues and committed it to my branch.. will it automatically be picked up here?

**Comment by devoh747** [comment]
Here is a test program to show how I calculated
 the static CRC command codes.. and to verify my dynamic CRC generation code.
[crc_verification_code.py.txt](https://github.com/adafruit/Adafruit_CircuitPython_SD/files/3481539/crc_verification_code.py.txt)

**Review by tannewt — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
