### PR TITLE
Make compatible with native adafruit_bus_device

### LINKED ISSUE #42: sdcard demo missing baudrate attribute on Raspberry Pi Pico
After adafruit/circuitpython#4114 was closed, I tested a Pico with adafruit-circuitpython-raspberry_pi_pico-en_US-20210202-9140bfb.uf2 and the latest library bundle as 20210203. I modified the pin numbers in the demo and it still draws an error:
`Traceback (most recent call last):
  File "code.py", line 23, in <module>
  File "adafruit_sdcard.py", line 101, in __init__
  File "adafruit_sdcard.py", line 122, in _init_card
  File "adafruit_sdcard.py", line 111, in _clock_card
AttributeError: 'SPIDevice' object has no attribute 'baudrate'`
My modified demo code is attached:
[code.txt](https://github.com/adafruit/circuitpython/files/5918448/code.txt)

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #42.

Make compatible with native `adafruit_bus_device` module:

- Stop looking inside the `SPIDevice`s that are created.
- Reorder code so constructor creates both initialization and operational `SPIDevice`.
- Refactor to incorporate single-use reset routine into initialization routine.

@jfabernathy try it out if you like.

Tested on a PyPortal with the latest `main` CircuitPython build.

### CODE REVIEW

**Review by jepler — CHANGES_REQUESTED** [review]
Can you double check the management of the chip select line during the inlined _clock_card?  I think one reason the original code is weird and doesn't use self._spi directly is that it needs to drive an unusual value onto the active-low chip_select pin. (it's active-low, right?)

Perhaps _init_card should be passed spi, cs.  It would then do the weird _clock_card step, then construct its own local spi_device object?

**Comment by dhalbert** [comment]
Thanks @jepler for pointing out my error. My SD card seems to tolerate not actually doing the 74-81 clock cycles and still works. It was easiest to just force CS high inside the `with`, rather than write extra setup code for the initialization.

**Comment by jfabernathy** [comment]
I only tested this on the Raspbery Pi Pico. I tested both the simple test that prints out the directory of files, and a program that logs the cpu[0] temperature to the sdcard.  Both work after you change the board.??? to match the board.GP? numbers the Pico uses. In my case SCK = GP2, MOSI = GP3, MISO= GP4, and CS=GP5.

**Review by jepler — APPROVED** [review]
Thanks, this addresses what I raised in the earlier issue

**Pull request merged**
